import { ref } from 'vue'

const messages = {
  zh: {
    message: {
      app_name: 'AI 竞品调研助手',
      app_subtitle: '竞品分析工作台',
      home_title: '新建调研任务',
      home_brief_heading: '定义问题和竞品范围',
      specify_competitors: '指定对比对象',
      home_brief_desc: '输入调研目标，指定要对比的网站。每个网站都可以单独配置登录页和账号密码。',
      research_query: '调研目标',
      query_placeholder: '例如：我想做一个多模态 AI 接口聚合平台，现在需要分析竞品的能力矩阵、定价策略和接入体验',
      competitor_urls: '竞品网站',
      add_competitor: '添加网站',
      enable_search: '自动搜索竞品',
      generate_prd: '生成 PRD',
      start_research: '开始调研',
      progress: '进度',
      report: '报告',
      prd: 'PRD',
      sources: '来源',
      followup: '追问',
      review: '审查',
      settings: '设置',
      history: '历史报告',
      sync: '同步',
      health: '健康',
      loading: '加载中...',
      error: '错误',
      success: '成功',
      cancel: '取消',
      confirm: '确认',
      delete: '删除',
      save: '保存',
      language: '语言',
      chinese: '中文',
      english: 'English',
      advanced_options: '高级选项',
      auto_search_hint: '没有指定网站时建议开启；已经输入明确竞品时可关闭，避免混入无关站点。',
      task_this_run: '本次任务',
      specified_sites: '指定网站',
      needs_login: '需登录',
      auto_search: '自动搜索',
      on: '开启',
      off: '关闭',
      this_deliverable: '本次交付',
      competitor_report: '竞品分析报告',
      report_default_desc: '默认生成，包含结论、来源和质量提示',
      prd_product_doc: 'PRD 产品需求文档',
      prd_auto_generate: '报告完成后自动继续生成',
    }
  },
  en: {
    message: {
      app_name: 'AI Competitive Research Assistant',
      app_subtitle: 'Competitive Analysis Workspace',
      home_title: 'New Research Task',
      home_brief_heading: 'Define Questions and Competitor Scope',
      specify_competitors: 'Specify Comparison Targets',
      home_brief_desc: 'Enter your research objective and specify sites to compare. Each site can be configured with its own login page and credentials.',
      research_query: 'Research Objective',
      query_placeholder: 'e.g., I want to build a multimodal AI interface aggregation platform, now I need to analyze the capability matrix, pricing strategy, and integration experience of competitors',
      competitor_urls: 'Competitor Sites',
      add_competitor: 'Add Site',
      enable_search: 'Auto-search Competitors',
      generate_prd: 'Generate PRD',
      start_research: 'Start Research',
      progress: 'Progress',
      report: 'Report',
      prd: 'PRD',
      sources: 'Sources',
      followup: 'Follow-up',
      review: 'Review',
      settings: 'Settings',
      history: 'Reports',
      sync: 'Sync',
      health: 'Health',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      cancel: 'Cancel',
      confirm: 'Confirm',
      delete: 'Delete',
      save: 'Save',
      language: 'Language',
      chinese: '中文',
      english: 'English',
      advanced_options: 'Advanced Options',
      auto_search_hint: 'Enable when no sites are specified; disable when you have already listed clear competitors to avoid unrelated sites.',
      task_this_run: 'This Task',
      specified_sites: 'Specified Sites',
      needs_login: 'Needs Login',
      auto_search: 'Auto Search',
      on: 'On',
      off: 'Off',
      this_deliverable: 'This Deliverable',
      competitor_report: 'Competitive Analysis Report',
      report_default_desc: 'Generated by default, includes conclusions, sources and quality notes',
      prd_product_doc: 'PRD Product Requirements Document',
      prd_auto_generate: 'Automatically generated after report completion',
    }
  }
};

const locale = ref(localStorage.getItem('locale') || 'zh')

function readMessage(key, lang) {
  return key.split('.').reduce((value, part) => value?.[part], messages[lang])
}

function t(key) {
  return readMessage(key, locale.value) || readMessage(key, 'zh') || key
}

export function useI18n() {
  return { locale, t }
}

const i18n = {
  install(app) {
    app.provide('i18n', { locale, t })
    app.config.globalProperties.$t = t
  }
}

export default i18n;
